# Generated by Django 4.1.9 on 2023-05-06 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = []
