# Generated by Django 4.1.9 on 2023-05-06 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20230506_1722"),
    ]

    operations = []
