# Generated by Django 4.1.9 on 2023-05-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_auto_20230506_1728"),
    ]

    operations = []
